%% Browser demo runner for canvas_app — see that module for the actual
%% drawing logic (pure Erlang, compiled to JS, animating a <canvas>
%% element via the canvas:* BIFs).
%%
%% Start with: rebar3 as example shell
%% Then call:  canvas_demo:build().   %% compiles canvas_app -> priv/js/demo/canvas/canvas_app.js
%%             canvas_demo:serve().   %% http://localhost:8768
-module(canvas_demo).
-export([build/0, serve/0, serve/1]).

%% Compile canvas_app from its BEAM (same path the real build pipeline
%% takes: beam reader -> IR -> encoder) and write it into this demo's
%% own subdirectory.
build() ->
    JS = concrete:compile_module(canvas_app),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo", "canvas"]),
    OutFile = filename:join(DemoDir, "canvas_app.js"),
    Header = <<"// Generated by Concrete -- do not edit. Source: example/canvas_app.erl\n">>,
    ok = file:write_file(OutFile, <<Header/binary, JS/binary>>),
    io:format("Wrote ~s~n", [OutFile]),
    ok.

serve() ->
    serve(8768).

serve(Port) ->
    concrete_dev_reload:ensure_started(),
    build(),
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir   = filename:join([code:priv_dir(concrete), "js", "demo"]),
    IndexFile = filename:join(DemoDir, "canvas/index.html"),
    Dispatch  = cowboy_router:compile([
        {'_', [
            {"/",        cowboy_static, {file, IndexFile}},
            {"/[...]",   cowboy_static, {dir,  DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(canvas_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    io:format("~nCanvas demo running at http://localhost:~w~n", [Port]).
