%% Interactive demo of the Concrete compiler pipeline.
%% Start with: rebar3 shell
%% Then call:  concrete_demo:hello_world().
%%             concrete_demo:build().   %% regenerate priv/js/demo/counter/counter.js
%%             concrete_demo:serve().
%%             concrete_demo:bundle().  %% call graph + dead-code elimination
%%             concrete_demo:wire().    %% wire-format round-trip
%%             concrete_demo:render().  %% template parse + server render + client JS
-module(concrete_demo).
-include("concrete_ir.hrl").
-export([hello_world/0, run/1, build/0, serve/0, serve/1, bundle/0, wire/0,
         render/0]).

%% Compile a hardcoded hello world component and print the JS.
hello_world() ->
    Src =
        """
        -module(hello).
        greet(Name) -> {ok, Name}.
        add(A, B) -> A + B.
        label(ok) -> done;
        label(error) -> failed.
        """,
    run(Src).

%% Compile an arbitrary Erlang source string and print the JS.
run(Src) ->
    io:format("~n=== SOURCE ===~n~s~n", [Src]),
    JS = compile_to_js(Src),
    io:format("=== GENERATED JAVASCRIPT ===~n~s~n", [JS]).

%% Erlang source for the browser counter demo. The whole loop lives in
%% Erlang: it writes to the DOM via the dom BIF module and reschedules
%% itself. JS only boots counter:start/0.
counter_src() ->
    """
    -module(counter).
    -export([start/0, tick/1]).
    start() ->
        tick(0).
    tick(N) ->
        dom:append_html(<<"output">>, integer_to_binary(N)),
        dom:append_html(<<"output">>, <<"<br>">>),
        dom:set_timeout(250, counter, tick, [N + 1]).
    """.

%% Compile the counter module and write the generated JS into the
%% demo directory served by serve/0.
build() ->
    Src = counter_src(),
    JS  = compile_to_js(Src),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo", "counter"]),
    OutFile = filename:join(DemoDir, "counter.js"),
    Header = ["// Generated by Concrete — do not edit.\n// Source:\n",
              [["//   ", Line, "\n"]
               || Line <- string:split(Src, "\n", all), Line =/= ""],
              "\n"],
    ok = file:write_file(OutFile, unicode:characters_to_binary([Header, JS])),
    io:format("Wrote ~s~n", [OutFile]),
    ok.

compile_to_js(Src) ->
    Forms = parse_source(Src),
    ModName = module_name(Forms),
    Ctx = concrete_transformer:new_ctx(ModName),
    IR  = concrete_transformer:transform_module(Forms, Ctx),
    concrete_encoder:encode_module(IR).

%% Start a cowboy static file server for the browser demo.
serve() ->
    serve(8765).

serve(Port) ->
    concrete_dev_reload:ensure_started(),
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir   = filename:join([code:priv_dir(concrete), "js", "demo"]),
    IndexFile = filename:join(DemoDir, "counter/index.html"),
    Dispatch  = cowboy_router:compile([
        {'_', [
            {"/",        cowboy_static, {file, IndexFile}},
            {"/[...]",   cowboy_static, {dir,  DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(concrete_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    URL = io_lib:format("http://localhost:~w", [Port]),
    io:format("~nDemo server running at ~s~n", [URL]),
    io:format("Open that URL in your browser, then Ctrl+C to stop.~n").

%% Phase 2 demo: compile a page module to BEAM, read its IR back out of
%% the beam, cache it in a PLT, build the call graph from the page entry
%% points, and emit a dead-code-eliminated JS bundle.
bundle() ->
    Src = shapes_src(),
    io:format("~n=== SOURCE ===~n~s~n", [Src]),
    Forms = parse_source(Src),
    ModName = module_name(Forms),

    %% Compile to BEAM in memory (with debug_info), then extract IR from
    %% the beam — the same path the real build pipeline takes.
    {ok, ModName, Beam} = compile:forms(Forms, [debug_info, binary]),
    {ok, #ir_module{definitions = Defs}} = concrete_beam_reader:extract_ir(Beam),

    %% Cache each function's IR in the PLT, keyed by MFA.
    PLT = concrete_plt:new(),
    [concrete_plt:put(PLT, {ModName, N, A}, D)
     || #ir_function_def{name = N, arity = A} = D <- Defs],

    %% Call graph rooted at the page entry points: init/2 and template/0.
    Graph     = concrete_call_graph:build(ModName, PLT),
    Reachable = concrete_call_graph:reachable(Graph),
    All       = lists:sort(concrete_plt:all_mfas(PLT)),
    Dead      = All -- Reachable,
    io:format("=== ALL FUNCTIONS ===~n~p~n~n", [All]),
    io:format("=== REACHABLE FROM init/2 + template/0 ===~n~p~n~n",
              [lists:sort(Reachable)]),
    io:format("=== ELIMINATED (dead code) ===~n~p~n~n", [Dead]),

    JS = concrete_encoder:encode_bundle(Graph, PLT),
    io:format("=== BUNDLE JAVASCRIPT ===~n~s~n", [JS]),
    digraph:delete(Graph),
    ok.

shapes_src() ->
    """
    -module(shapes).
    -export([init/2, template/0, perimeter/2]).
    init(_Params, Server) ->
        {#{state => #{area => area(3, 4)}}, Server}.
    template() ->
        banner().
    banner() -> <<"** shapes **">>.
    area(W, H) -> W * H.
    perimeter(W, H) -> double(W + H).  %% dead: never called from an entry point
    double(X) -> X * 2.                %% dead transitively (only perimeter calls it)
    """.

%% Phase 4 demo: round-trip an Erlang term through the type-tagged JSON
%% wire format (serializer -> JSON text -> deserializer).
wire() ->
    Term = #{count => 42,
             label => <<"clicks">>,
             history => [1, 2, 3],
             status => {ok, ready}},
    io:format("~n=== TERM ===~n~p~n~n", [Term]),
    Tagged = concrete_serializer:encode(Term),
    Json   = thoas:encode(Tagged),
    io:format("=== WIRE JSON ===~n~s~n~n", [Json]),
    {ok, Decoded} = thoas:decode(Json),
    Term2 = concrete_deserializer:decode(Decoded),
    io:format("=== DECODED ===~n~p~n~n", [Term2]),
    io:format("Round-trip equal: ~p~n", [Term =:= Term2]),
    ok.

%% Phase 3 demo: parse a .slab template into a DOM AST, render it
%% server-side against component state, and compile it into a client
%% render/1 function as JavaScript.
render() ->
    Template =
        """
        <div class="scoreboard">
          <h1>{@title}</h1>
          <p>Next score: {@score + 1}</p>
          <button concrete-click="increment">+</button>
        </div>
        """,
    io:format("~n=== TEMPLATE (.slab) ===~n~s~n~n", [Template]),

    DOM = concrete_template_parser:parse_string(Template),
    io:format("=== DOM AST ===~n~p~n~n", [DOM]),

    State = #{state => #{title => <<"Scores">>, score => 41}},
    HTML = concrete_renderer:render_nodes(DOM, State),
    io:format("=== SERVER-RENDERED HTML (state: ~0p) ===~n~s~n~n",
              [maps:get(state, State), HTML]),

    FunDef = concrete_template_parser:compile_render_fun(DOM),
    JS = concrete_encoder:encode_function_def(scoreboard, FunDef),
    io:format("=== CLIENT RENDER FUNCTION (JS) ===~n~s~n", [JS]),
    ok.

%% --- Helpers ---

parse_source(Src) ->
    {ok, Tokens, _} = erl_scan:string(Src),
    parse_forms(Tokens, []).

parse_forms([], Acc) ->
    lists:reverse(Acc);
parse_forms(Tokens, Acc) ->
    case split_at_dot(Tokens) of
        {[], _} ->
            lists:reverse(Acc);
        {FormTokens, Rest} ->
            case erl_parse:parse_form(FormTokens) of
                {ok, Form} -> parse_forms(Rest, [Form | Acc]);
                _          -> parse_forms(Rest, Acc)
            end
    end.

split_at_dot(Tokens) ->
    split_at_dot(Tokens, []).

split_at_dot([], Acc) ->
    {lists:reverse(Acc), []};
split_at_dot([{dot, _} = D | Rest], Acc) ->
    {lists:reverse([D | Acc]), Rest};
split_at_dot([H | T], Acc) ->
    split_at_dot(T, [H | Acc]).

module_name(Forms) ->
    hd([Name || {attribute, _, module, Name} <- Forms] ++ [unnamed]).
