%% Browser demo runner for the gen_server example -- see
%% concrete_gen_server.erl (the generic loop), counter_server.erl (the
%% callback module) and counter_ui.erl (the DOM wiring).
%%
%% Start with: rebar3 as example shell
%% Then call:  gen_server_demo:build().  %% compiles all three modules
%%             gen_server_demo:serve().  %% http://localhost:8769
-module(gen_server_demo).
-export([build/0, serve/0, serve/1]).

modules() ->
    [concrete_gen_server, counter_server, counter_ui].

%% Compile each module from its BEAM (same path the real build
%% pipeline takes: beam reader -> IR -> encoder) and write it next to
%% the other demo assets. Each becomes its own <script> tag; dynamic
%% cross-module dispatch is resolved at runtime (see
%% Interpreter.defineErlangFunction in runtime.js), so load order
%% between them doesn't matter as long as all three load before boot.
build() ->
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo", "gen_server"]),
    lists:foreach(fun(Mod) ->
        JS = concrete:compile_module(Mod),
        OutFile = filename:join(DemoDir, atom_to_list(Mod) ++ ".js"),
        Header = <<"// Generated by Concrete -- do not edit.\n">>,
        ok = file:write_file(OutFile, <<Header/binary, JS/binary>>),
        io:format("Wrote ~s~n", [OutFile])
    end, modules()),
    ok.

serve() ->
    serve(8769).

serve(Port) ->
    concrete_dev_reload:ensure_started(),
    build(),
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir   = filename:join([code:priv_dir(concrete), "js", "demo"]),
    IndexFile = filename:join(DemoDir, "gen_server/index.html"),
    Dispatch  = cowboy_router:compile([
        {'_', [
            {"/",        cowboy_static, {file, IndexFile}},
            {"/[...]",   cowboy_static, {dir,  DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(gen_server_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    io:format("~nGen-server demo running at http://localhost:~w~n", [Port]).
