%% Browser demo runner for process_viz_app -- see that module for the
%% actual spawn/self/!/receive logic and the ring visualization.
%%
%% Start with: rebar3 as example shell
%% Then call:  process_viz_demo:build().  %% compiles process_viz_app -> priv/js/demo/process_viz/process_viz_app.js
%%             process_viz_demo:serve().  %% http://localhost:8770
-module(process_viz_demo).
-export([build/0, serve/0, serve/1]).

%% Compile process_viz_app from its BEAM (same path the real build
%% pipeline takes: beam reader -> IR -> encoder) and write it into
%% this demo's own subdirectory.
build() ->
    JS = concrete:compile_module(process_viz_app),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo", "process_viz"]),
    OutFile = filename:join(DemoDir, "process_viz_app.js"),
    Header = <<"// Generated by Concrete -- do not edit. Source: example/process_viz_app.erl\n">>,
    ok = file:write_file(OutFile, <<Header/binary, JS/binary>>),
    io:format("Wrote ~s~n", [OutFile]),
    ok.

serve() ->
    serve(8770).

serve(Port) ->
    concrete_dev_reload:ensure_started(),
    build(),
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir   = filename:join([code:priv_dir(concrete), "js", "demo"]),
    IndexFile = filename:join(DemoDir, "process_viz/index.html"),
    Dispatch  = cowboy_router:compile([
        {'_', [
            {"/",        cowboy_static, {file, IndexFile}},
            {"/[...]",   cowboy_static, {dir,  DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(process_viz_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    io:format("~nProcess-viz demo running at http://localhost:~w~n", [Port]).
