%% Browser demo runner for multiplayer snake -- see snake_game.erl (the
%% authoritative gen_server), snake_http.erl / snake_sse_handler.erl
%% (the HTTP/SSE plumbing) and snake_client.erl (the compiled-to-JS
%% rendering + input half).
%%
%% Start with: rebar3 as example shell
%% Then call:  snake_demo:serve().  %% http://localhost:8771
%% Open the same URL in a second tab (or another browser) to see two
%% snakes moving independently, in sync, on both screens.
-module(snake_demo).
-export([build/0, serve/0, serve/1]).

%% Compile snake_client from its BEAM (same path the real build
%% pipeline takes: beam reader -> IR -> encoder) and write it into
%% this demo's own subdirectory.
build() ->
    JS = concrete:compile_module(snake_client),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo", "snake"]),
    OutFile = filename:join(DemoDir, "snake_client.js"),
    Header = <<"// Generated by Concrete -- do not edit. Source: example/snake_client.erl\n">>,
    ok = file:write_file(OutFile, <<Header/binary, JS/binary>>),
    io:format("Wrote ~s~n", [OutFile]),
    ok.

serve() ->
    serve(8771).

serve(Port) ->
    build(),
    ensure_game_started(),
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo"]),
    Dispatch = cowboy_router:compile([
        {'_', [
            {"/",                        snake_http,        #{route => page}},
            {"/snake/input",             snake_http,         #{route => input}},
            {"/snake/heartbeat",         snake_http,         #{route => heartbeat}},
            {"/snake/events/:secret", snake_sse_handler,  #{}},
            {"/assets/[...]",            cowboy_static,
                {dir, DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(snake_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch},
        %% The SSE stream is one-directional (server -> browser); cowboy's
        %% idle_timeout only resets on data *received* from the client, so
        %% with the default 60000ms this connection would get killed by
        %% cowboy itself every 60s regardless of the heartbeats flowing
        %% out over it, and EventSource would silently reconnect.
        idle_timeout => infinity
    }),
    io:format("~nSnake demo running at http://localhost:~w~n", [Port]).

ensure_game_started() ->
    case whereis(snake_game) of
        undefined -> {ok, _} = snake_game:start_link(), ok;
        _Pid      -> ok
    end.
