%% Browser demo runner for spirograph_app -- see that module for the
%% actual three.js scene (pure Erlang, compiled to JS, calling into
%% three.js via concrete_js).
%%
%% Start with: rebar3 as example shell
%% Then call:  spirograph_demo:build().  %% compiles spirograph_app -> priv/js/demo/spirograph/spirograph_app.js
%%             spirograph_demo:serve().  %% http://localhost:8773
-module(spirograph_demo).
-export([build/0, serve/0, serve/1]).

%% Compile spirograph_app from its BEAM (same path the real build
%% pipeline takes: beam reader -> IR -> encoder) and write it into this
%% demo's own subdirectory.
build() ->
    JS = concrete:compile_module(spirograph_app),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo", "spirograph"]),
    OutFile = filename:join(DemoDir, "spirograph_app.js"),
    Header = <<"// Generated by Concrete -- do not edit. Source: example/spirograph_app.erl\n">>,
    ok = file:write_file(OutFile, <<Header/binary, JS/binary>>),
    io:format("Wrote ~s~n", [OutFile]),
    ok.

serve() ->
    serve(8773).

serve(Port) ->
    build(),
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir   = filename:join([code:priv_dir(concrete), "js", "demo"]),
    IndexFile = filename:join(DemoDir, "spirograph/index.html"),
    Dispatch  = cowboy_router:compile([
        {'_', [
            {"/",        cowboy_static, {file, IndexFile}},
            {"/[...]",   cowboy_static, {dir,  DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(spirograph_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    io:format("~nSpirograph demo running at http://localhost:~w~n", [Port]).
