%% Browser demo for <:for> + persistent per-instance <:component> state
%% + mount/2 (see component-mount-plan.md) -- a small task board where
%% each task is its own live child component, not just markup.
%%
%% Start with: rebar3 as example shell
%% Then call:  task_board_demo:serve().
%% Open:       http://localhost:8774
%%
%% Same shape as template_demo.erl (server-rendered first load, then
%% hydrated for client-side action dispatch), except the client bundle
%% has to carry two modules -- the page and its child component -- so
%% bundle_js/1 concatenates both, the same way rebar_compiler_concrete
%% would for any page that embeds a <:component>.
-module(task_board_demo).
-behaviour(cowboy_handler).

-export([serve/0, serve/1, init/2]).

serve() ->
    serve(8774).

serve(Port) ->
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo"]),
    Dispatch = cowboy_router:compile([
        {'_', [
            {"/",          ?MODULE, #{route => page}},
            {"/bundle.js", ?MODULE, #{route => bundle}},
            {"/[...]",     cowboy_static, {dir, DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(task_board_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    io:format("~nTask board demo running at http://localhost:~w~n", [Port]).

init(Req, #{route := bundle} = State) ->
    Req2 = cowboy_req:reply(200,
        #{<<"content-type">> => <<"application/javascript; charset=utf-8">>},
        bundle_js([task_board_page, task_item]),
        Req),
    {ok, Req2, State};
init(Req, #{route := page} = State) ->
    {HTML, StateJSON, _Server} = concrete_renderer:render_page(task_board_page, #{}),
    Req2 = cowboy_req:reply(200,
        #{<<"content-type">> => <<"text/html; charset=utf-8">>},
        page_shell(HTML, StateJSON),
        Req),
    {ok, Req2, State}.

%% Compile every module's own BEAM (beam reader -> IR -> encoder) plus
%% its own compiled template render function, concatenated into one
%% script -- mirrors what rebar_compiler_concrete:compile/4 does for a
%% page bundle that embeds <:component>s (see client_SUITE's
%% module_and_render_js/1 for the same pattern in tests).
bundle_js(Modules) ->
    Parts = [begin
        {ok, IR} = concrete_beam_reader:extract_ir(Mod),
        ModuleJS = concrete_encoder:encode_module(IR),
        {inline, DOM} = Mod:template(),
        RenderJS = concrete_encoder:encode_function_def(
                       Mod, concrete_template_parser:compile_render_fun(DOM)),
        [ModuleJS, RenderJS]
    end || Mod <- Modules],
    unicode:characters_to_binary(
        [<<"// Generated by Concrete -- task board demo bundle\n">>, Parts]).

page_shell(HTML, StateJSON) ->
    [<<"<!DOCTYPE html>\n"
       "<html lang=\"en\">\n<head>\n"
       "  <meta charset=\"UTF-8\">\n"
       "  <title>Concrete -- task board</title>\n"
       "  <link rel=\"stylesheet\" href=\"/theme.css\">\n"
       "  <style>\n"
       "    .board { max-width: 28rem; border: 1px solid var(--border);\n"
       "             border-radius: var(--radius); background: var(--bg-panel);\n"
       "             padding: 1rem 2rem; }\n"
       "    .task { display: flex; justify-content: space-between; align-items: center;\n"
       "            padding: 0.4rem 0; border-bottom: 1px solid var(--border); }\n"
       "    .mount-flag { color: var(--accent); font-size: 0.85rem; }\n"
       "    .board input { margin-top: 1rem; padding: 0.3rem 0.5rem; }\n"
       "    .board button { margin-top: 1rem; margin-left: 0.5rem; }\n"
       "    .caveat { max-width: 56rem; border-left: 3px solid var(--accent);\n"
       "              padding: 0.5rem 1.5rem; margin: 2rem 0 1rem; font-size: 0.9rem; }\n"
       "  </style>\n"
       "</head>\n<body>\n"
       "  <a class=\"back-link\" href=\"http://localhost:8760/\">&larr; All demos</a>\n"
       "  <p>Each task in the list below is its own persistent "
       "     <code>task_item</code> component, keyed by id -- add one and its "
       "     <code>mount/2</code> fires exactly once, client-side; complete the "
       "     oldest and its instance is dropped, not just its markup. See "
       "     <code>component-mount-plan.md</code>.</p>\n"
       "  <div id=\"concrete-root\">\n">>,
     HTML,
     <<"\n  </div>\n"
       "  <p class=\"caveat\"><b>One thing worth knowing:</b> the \"mounted\" "
       "     flag next to an already-mounted task disappears the moment you "
       "     click Add task or Complete oldest again. That's not "
       "     <code>mount/2</code> re-firing -- it genuinely only runs once per "
       "     task, keyed identity and all. It's that every action here does a "
       "     full re-render (a fresh <code>innerHTML</code> for the whole "
       "     board), which overwrites the plain DOM text <code>mount/2</code> "
       "     wrote earlier outside the template. Real diffing would leave it "
       "     alone; a full re-render can't tell the difference.</p>\n"
       "  <script src=\"/runtime.js\"></script>\n"
       "  <script src=\"/client.js\"></script>\n"
       "  <script src=\"/bundle.js\"></script>\n"
       "  <script>\n"
       "    Client.init(\"task_board_page\", \"concrete-root\", ">>,
     StateJSON,
     <<");\n"
       "  </script>\n"
       "</body>\n</html>\n">>].
