%% Browser demo for the template system + client-side actions.
%%
%% Start with: rebar3 shell
%% Then call:  template_demo:serve().
%% Open:       http://localhost:8766
%%
%% Server side: every request is rendered on the spot —
%% scoreboard_page:init/2 builds state from the query params, the
%% .slab template (priv/templates/scoreboard.slab) is parsed, and
%% concrete_renderer evaluates the {@...} expressions with erl_eval.
%%
%% Client side: /bundle.js is generated from scoreboard_page's BEAM
%% (beam reader -> IR -> encoder) plus the compiled template render
%% function. client.js hydrates the server state JSON and dispatches
%% concrete-click actions to the compiled action/3 — the + / - buttons
%% run Erlang in the browser.
-module(template_demo).
-behaviour(cowboy_handler).

-export([serve/0, serve/1, init/2]).

serve() ->
    serve(8766).

serve(Port) ->
    {ok, _} = application:ensure_all_started(cowboy),
    TemplatesDir = filename:join(code:priv_dir(concrete), "templates"),
    application:set_env(concrete, templates_dir, TemplatesDir),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo"]),
    Dispatch = cowboy_router:compile([
        {'_', [
            {"/",            ?MODULE, #{route => page}},
            {"/bundle.js",   ?MODULE, #{route => bundle}},
            {"/assets/[...]", cowboy_static,
                {dir, DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(template_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    io:format("~nTemplate demo running at http://localhost:~w~n", [Port]),
    io:format("Try http://localhost:~w/?player=sam&score=100~n", [Port]).

init(Req, #{route := bundle} = State) ->
    Req2 = cowboy_req:reply(200,
        #{<<"content-type">> => <<"application/javascript; charset=utf-8">>},
        bundle_js(scoreboard_page),
        Req),
    {ok, Req2, State};
init(Req, #{route := page} = State) ->
    Params = parse_query_params(Req),
    {HTML, StateJSON, _Server} = concrete_renderer:render_page(scoreboard_page, Params),
    Req2 = cowboy_req:reply(200,
        #{<<"content-type">> => <<"text/html; charset=utf-8">>},
        page_shell(HTML, StateJSON),
        Req),
    {ok, Req2, State}.

%% Compile the page module (from its BEAM, same as the build pipeline)
%% plus its template render function into one JS bundle.
bundle_js(PageModule) ->
    {ok, IR} = concrete_beam_reader:extract_ir(PageModule),
    ModuleJS = concrete_encoder:encode_module(IR),
    TemplatesDir = filename:join(code:priv_dir(concrete), "templates"),
    DOM = case PageModule:template() of
        {inline, D} -> D;
        File        -> concrete_template_parser:parse_file(
                           filename:join(TemplatesDir, File))
    end,
    RenderJS = concrete_encoder:encode_function_def(
                   PageModule,
                   concrete_template_parser:compile_render_fun(DOM)),
    unicode:characters_to_binary(
        ["// Generated by Concrete — page bundle for ", atom_to_binary(PageModule),
         "\n", ModuleJS, RenderJS]).

parse_query_params(Req) ->
    maps:from_list([{binary_to_atom(K), V} || {K, V} <- cowboy_req:parse_qs(Req)]).

%% Wrap the server-rendered fragment in a full HTML page that boots the
%% client: hydrate the state JSON, then buttons dispatch to compiled
%% Erlang.
page_shell(HTML, StateJSON) ->
    [
     """
     <!DOCTYPE html>
     <html lang="en">
     <head>
       <meta charset="UTF-8">
       <title>Concrete — live scoreboard</title>
       <link rel="stylesheet" href="/assets/theme.css">
       <style>
         .scoreboard { max-width: 24rem; border: 1px solid var(--border);
                       border-radius: var(--radius); background: var(--bg-panel);
                       padding: 1rem 2rem; }
         .scoreboard button { font-size: 1.2rem; min-width: 2.5rem; }
       </style>
     </head>
     <body>
       <a class="back-link" href="http://localhost:8760/">&larr; All demos</a>
       <p>Server-rendered by <code>concrete_renderer:render_page/2</code>,
          then hydrated — the +/&#8722; buttons dispatch to the compiled
          <code>scoreboard_page:action/3</code> running in your browser.
          Query params re-render server-side:
          <a href="/?player=sam&score=100">/?player=sam&amp;score=100</a></p>
       <div id="concrete-root">
     """,
     HTML,
     """

       </div>
       <h2>Hydration payload</h2>
       <pre>
     """,
     escape_html(StateJSON),
     """
     </pre>
       <script src="/assets/runtime.js"></script>
       <script src="/assets/client.js"></script>
       <script src="/bundle.js"></script>
       <script>
         Client.init("scoreboard_page", "concrete-root",
     """,
     StateJSON,
     """
     );
       </script>
     </body>
     </html>
     """
    ].

escape_html(Bin) ->
    binary:replace(
        binary:replace(iolist_to_binary(Bin), <<"&">>, <<"&amp;">>, [global]),
        <<"<">>, <<"&lt;">>, [global]).
