%% Browser demo runner for todo_app — see that module for the actual
%% todo-list logic (pure Erlang, compiled to JS, persisted to
%% localStorage).
%%
%% Start with: rebar3 as example shell
%% Then call:  todo_demo:build().   %% compiles todo_app -> priv/js/demo/todo/todo.js
%%             todo_demo:serve().   %% http://localhost:8767
-module(todo_demo).
-export([build/0, serve/0, serve/1]).

%% Compile todo_app from its BEAM (same path the real build pipeline
%% takes: beam reader -> IR -> encoder) and write it into this demo's
%% own subdirectory.
build() ->
    JS = concrete:compile_module(todo_app),
    DemoDir = filename:join([code:priv_dir(concrete), "js", "demo", "todo"]),
    OutFile = filename:join(DemoDir, "todo.js"),
    Header = <<"// Generated by Concrete -- do not edit. Source: example/todo_app.erl\n">>,
    ok = file:write_file(OutFile, <<Header/binary, JS/binary>>),
    io:format("Wrote ~s~n", [OutFile]),
    ok.

serve() ->
    serve(8767).

serve(Port) ->
    build(),
    {ok, _} = application:ensure_all_started(cowboy),
    DemoDir   = filename:join([code:priv_dir(concrete), "js", "demo"]),
    IndexFile = filename:join(DemoDir, "todo/index.html"),
    Dispatch  = cowboy_router:compile([
        {'_', [
            {"/",        cowboy_static, {file, IndexFile}},
            {"/[...]",   cowboy_static, {dir,  DemoDir, [{mimetypes, cow_mimetypes, all}]}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(todo_demo_http, [{port, Port}], #{
        env => #{dispatch => Dispatch}
    }),
    io:format("~nTodo demo running at http://localhost:~w~n", [Port]).
