%% Compiles {{name}} to JavaScript and drops it (plus the browser runtime)
%% next to priv/index.html. No cowboy, no server -- just files on disk.
%%
%% Start with: rebar3 shell
%% Then call:  {{name}}_build:build().
%% Then open:  priv/index.html directly in a browser.
-module({{name}}_build).
-export([build/0]).

build() ->
    JS = concrete:compile_module({{name}}),
    Header = <<"// Generated by Concrete -- do not edit. Source: src/{{name}}.erl\n">>,
    ok = file:write_file("priv/{{name}}.js", <<Header/binary, JS/binary>>),
    {ok, _} = file:copy(concrete:runtime_path(), "priv/runtime.js"),
    io:format("Wrote priv/{{name}}.js and priv/runtime.js~n"),
    ok.
