// Generated by Concrete — do not edit.
// Source:
//   -module(counter).
//   -export([start/0, tick/1]).
//   start() ->
//       tick(0).
//   tick(N) ->
//       dom:append_html(<<"output">>, integer_to_binary(N)),
//       dom:append_html(<<"output">>, <<"<br>">>),
//       dom:set_timeout(250, counter, tick, [N + 1]).

// Module: counter
Interpreter.defineErlangFunction("counter", "start", 0, ((currentModule) => [
  [(args) => { const bindings = {}; return bindings; }, (_bindings) => true, (bindings) => { return Interpreter.call(currentModule, "tick", 1, [Type.integer(0)]); }]])("counter"));
Interpreter.defineErlangFunction("counter", "tick", 1, ((currentModule) => [
  [(args) => { const bindings = {}; bindings["N"] = args[0]; return bindings; }, (_bindings) => true, (bindings) => { Erlang["dom:append_html/2"](Type.bitstring("output"), Interpreter.call(currentModule, "integer_to_binary", 1, [bindings["N"]])); Erlang["dom:append_html/2"](Type.bitstring("output"), Type.bitstring("<br>")); return Erlang["dom:set_timeout/4"](Type.integer(250), Type.atom("counter"), Type.atom("tick"), Erlang["++/2"](Type.list([Erlang["+/2"](bindings["N"], Type.integer(1))]), Type.list([]))); }]])("counter"));
