// Generated by Concrete — do not edit.
// Source:
//   -module(hello).
//   greet(Name) -> {ok, Name}.
//   add(A, B) -> A + B.
//   label(ok) -> done;
//   label(error) -> failed.

Interpreter.defineErlangFunction("hello", "greet", 1, [
  [
    (args) => { const bindings = {}; bindings["Name"] = args[0]; return bindings; },
    (_bindings) => true,
    (bindings) => { return Type.tuple([Type.atom("ok"), bindings["Name"]]); }
  ]
]);

Interpreter.defineErlangFunction("hello", "add", 2, [
  [
    (args) => { const bindings = {}; bindings["A"] = args[0]; bindings["B"] = args[1]; return bindings; },
    (_bindings) => true,
    (bindings) => { return Erlang["+/2"](bindings["A"], bindings["B"]); }
  ]
]);

Interpreter.defineErlangFunction("hello", "label", 1, [
  [
    (args) => { const bindings = {}; if (!(Interpreter.isEqual(args[0], Type.atom("ok"))))    return null; return bindings; },
    (_bindings) => true,
    (_bindings) => { return Type.atom("done"); }
  ],
  [
    (args) => { const bindings = {}; if (!(Interpreter.isEqual(args[0], Type.atom("error")))) return null; return bindings; },
    (_bindings) => true,
    (_bindings) => { return Type.atom("failed"); }
  ]
]);
